---
title: "Advent of Code 2020"
author: "Matthew Monterosso"
date: "12/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Day 1: Report Repair


```{r}

#First get Data from web
library(tidyverse)
library(rvest)
library(xml2)


df <- read.delim("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD1.txt", header = FALSE)



##not sure why cant dl from web - getting 400 Bad Req Error

# download.file(url, "CodeAdventDay1.html", quiet = TRUE)
# 
# df <- read_html("https://adventofcode.com/2020/day/1/input") 


#this is likely not a scalable solution, but will work here
#also the expand does by itself as combo but we could filter this out if needed but there is no 1001 so wont be an issue



df_expand <- expand.grid(df$V1,df$V1) %>%
  mutate(ExpenseSum = Var1 + Var2) %>%
  filter(ExpenseSum == 2020) %>%
  mutate(Answer = Var1 * Var2)
  

##Day 1 Part Two


#yeah this wont scale - 8MM points still doable on there's gotta be better way

df_expand <- expand.grid(df$V1,df$V1)

df_super_expand <- expand.grid(df$V1,df$V1,df$V1) %>%
  mutate(ExpenseSum = Var1 + Var2 + Var3) %>%
  filter(ExpenseSum == 2020) %>%
  mutate(Answer = Var1 * Var2 * Var3)



```

## Day 2: Password Philosophy WIP


```{r}

df2 <- read.delim("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD2.txt", header = FALSE, sep = " ") %>%
  mutate(V2 = substr(V2,1,1),
         MinNum = str_extract(V1,"^\\d{1,2}"),
          MaxNum = str_extract(V1,"\\d{1,2}$"),
         valid = ifelse(between(str_count(V3, V2), MinNum, MaxNum),1, 0))

sum(df2$valid)


#Day 2 Part Two


lapply(str_split(df2$V3,""), str_which(pattern = "l"))


locs <- as.matrix(nrow = 1, ncol = max(nchar(str_split(df2$V3[1],""))))

for (i in 1:1000){

locs <-  rbind(locs, paste(stringr::str_which(unlist(str_split(df2$V3[i],"")),df2$V2[i])))
  
}


test <- paste(stringr::str_which(unlist(str_split(df2$V3[1],"")),df2$V2[1]))

stringr::str_which(unlist(str_split(df2$V3,"")),df2$V2)


###Soltion by kacey_kc check from Discord

day_2 <-  
  ## dropped my input into a csv file
  read_csv("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD2.txt", col_names = FALSE) %>%
  separate(X1, c("min","max","key","pass")) %>% 
  mutate_all(str_trim) %>% 
  mutate_at(c("min", "max"), as.numeric)

# I see so they explicitly took the locations, probably better idea than counting chars

day_2_2 <- 
  day_2 %>% 
  rowwise() %>% 
  mutate(
    pos1 = str_sub(pass, min, min),
    pos2 = str_sub(pass, max, max)
    ) %>%
  filter(xor(pos1 == key, pos2 == key))

print(nrow(day_2_2))


```


## Day 3: Toboggan Trajectory

```{r}

##first we need to determine how far we need to repeat pattern

df3 <- read.delim("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD3.txt", header = FALSE, sep = " ")

str_length(df3[2,1])

nrow(df3)

# 323 height x 31 paces dimensions

#via 3 right down 1, we will need x paces calculated as


ceiling((323 * 3) / 31)

# we will need to repeat the pattern 32 times to get to bottom


df3 <- df3 %>%
  mutate(Pattern = strrep(V1,32))


strrep(df3[1,1],32)


df3_wide <- df3 %>%
  separate(col = V1, into = paste0("col",0:31), sep = "") %>%
  select(-col0) %>%
  as.matrix(.)

##323 loop

tree_hits <- 0

for (i in 1:322){
  #browser()
  if (df3_wide[i + 1 , ifelse((i * 3 + 1) %% 31 == 0, 31,(i * 3 + 1) %% 31)] == "#") {
    print(paste0("tree hit at row ", i ))
    tree_hits <- tree_hits + 1
  }
  }

##correct @ 270


#now check other slopes

Right <- c(1,3,5,7,1)
Down <- c(1,1,1,1,2)

slopemap <- cbind(Right,Down)


for (slope in 1:5){
  tree_hits <- 0
  for (i in 1:322){
  #browser()
   if (df3_wide[i * slopemap[slope,2] + 1 , ifelse((i * slopemap[slope,1] + 1) %% 31 == 0, 31,(i * slopemap[slope,1] + 1) %% 31)] == "#") {
    #print(paste0("tree hit at row ", i ))
    tree_hits <- tree_hits + 1
  }
   
  }
  
  print(tree_hits) 
  
}

# [1] 80
# [1] 270
# [1] 60
# [1] 63




##brainstorm elegant way for case 5


  tree_hits <- 0
  for (i in 1:(322/2)){
  #browser()
   if (df3_wide[i * slopemap[5,2] + 1 , ifelse((i * slopemap[5,1] + 1) %% 31 == 0, 31,(i * slopemap[5,1] + 1) %% 31)] == "#") {
    #print(paste0("tree hit at row ", i ))
    tree_hits <- tree_hits + 1
  }
    print(tree_hits) 
  }
  
 #26 hits on final condition
  
  80*270*60*63*26
  





###

```

## Day 4: Passport Processing


```{r}



## solution from RStats Discord user Ravel - I'll break it apart for learning

##read in data, do NOT skip empty rows as those delimit our passports
## use this neat cumsum trick to basically auto-increment by one when a NA row, i.e our passport delimiter is found
## separate on spaces to columns as the bat
 
df4 <- read_delim("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD4.txt", delim = "\n", col_names = FALSE, skip_empty_rows = FALSE) %>% 
  mutate(passport = cumsum(is.na(X1))) %>%
   filter(!is.na(X1)) %>%
  separate_rows(X1, sep = " ") %>%
  separate(X1, into = c("type","value"), sep = ":") %>%
  pivot_wider(names_from = type, values_from = value) %>%
  #my addition, big yeet
  drop_na(eyr:iyr) %>% nrow(.)
  
  

##RULESET

# byr (Birth Year) - four digits; at least 1920 and at most 2002.
# iyr (Issue Year) - four digits; at least 2010 and at most 2020.
# eyr (Expiration Year) - four digits; at least 2020 and at most 2030.
# hgt (Height) - a number followed by either cm or in:
# If cm, the number must be at least 150 and at most 193.
# If in, the number must be at least 59 and at most 76.
# hcl (Hair Color) - a # followed by exactly six characters 0-9 or a-f.
# ecl (Eye Color) - exactly one of: amb blu brn gry grn hzl oth.
# pid (Passport ID) - a nine-digit number, including leading zeroes.
# cid (Country ID) - ignored, missing or not.


df4 <- read_delim("C:\\Users\\Matth\\Desktop\\SelfTeach\\Advent of Code 2020\\inputD4.txt", delim = "\n", col_names = FALSE, skip_empty_rows = FALSE) %>% 
  mutate(passport = cumsum(is.na(X1))) %>%
   filter(!is.na(X1)) %>%
  separate_rows(X1, sep = " ") %>%
  separate(X1, into = c("type","value"), sep = ":") %>%
  pivot_wider(names_from = type, values_from = value) %>%
  #my addition, big yeet
  drop_na(eyr:iyr) %>%
  filter(between(byr, 1920,2002)) %>%
  filter(between(iyr,2010,2020)) %>%
  filter(between(eyr,2020,2030)) %>%
  #filter(str_detect(hgt, "\\d+cm$|in$")) %>%
  filter(between(as.numeric(str_extract(str_extract(hgt, "\\d+in$"), "\\d+")), 59, 76) | between(as.numeric(str_extract(str_extract(hgt, "\\d+cm$"), "\\d+")), 150, 193))
  

  str_extract(df4$hgt, "\\d+cm$")
  between(as.numeric(str_extract(str_extract(df4$hgt, "\\d+in$"), "\\d+")),59,76)







```



